##############################
###### DEV Properties ########
##############################

spring:
  profiles: dev

server:
  port: 8080

application:
  cron: 0+0/1+10-23+?+*+MON-FRI

google-storage:
  file-name-prefix: ${PREFIX:Dan Millman}
  file-destination: word-counter-tmp
  ext: .txt
  bucket: word-counter-pld
  inbound: inbound/
  done: done/
  outbound: outbound/
  error: error/
