##############################
###### DEV Properties ########
##############################

spring:
  profiles: dev

server:
  port: 8080

application:
  cron-expression-workdays-each-minute: 0+0/1+10-23+?+*+MON-FRI
  file-destination-local: /word-counter-tmp/
  generated-file-name-prefix: Counted-
  downloaded: downloaded/
  counted: counted/

google-storage:
  file-name-prefix: ${PREFIX:Dan Millman}
  ext: .txt
  bucket: word-counter-pld
  inbound: inbound/
  done: done/
  outbound: outbound/
  error: error/
